CREATE TABLE PRODUCTS (
	PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    ORIGINALPRICE DECIMAL(18,2)
);
INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,CATEGORY,ORIGINALPRICE)
VALUES (1,'IPHONE 15','ELECTRONICS',20000000),
		(2,'SAMSUNG REFRIGERATOR', 'ELECTRONICS',15000000),
        (3,'WATER SPINACH','FOOD',10000),
        (4,'FILTERED FRESH MILK 4','FOOD',28000);
UPDATE PRODUCTS
SET ORIGINALPRICE = ORIGINALPRICE * 0.9
WHERE CATEGORY = ELECTRONICS;
/*
THIẾU WHERE= CONTIEN GÂY KHIẾN CHO CÂU LỆNH ĐÃ LẦM TƯỞNG WHERE= TRUE VÀ THỰC HIỆN GIẢM TẤT CẢ
*/